#!/usr/bin/bash

#Mejoras a futuro, elegir la organización de github para consultar
#Filtrar por ejercicio

gh repo list INGCOM-UNRN-P1  --limit=500 --json name,pushedAt,updatedAt | jq -r '(.[0] | keys_unsorted) as $keys | ([$keys] + map([.[ $keys[] ]])) [] | @csv' > status-$(date +%F).csv
