#!/usr/bin/bash

#Mejoras a futuro, elegir la organización de github para consultar
#Filtrar por ejercicio

gh repo list alumnos-ingcom  --limit=500 --json name,pushedAt,updatedAt | in2csv -f json > status-$(date +%F).csv
